



def financial_terms():
    financial_terms = {
        "Beta": {
            "Definition": "A measure of a stock’s volatility compared to the overall market.",
            "Formula": "None",
            "Interpretation": "β = 1: Market-level risk, β > 1: More volatile (risky), β < 1: Less volatile (safer)."
        },
        "Price-to-Earnings (P/E) Ratio": {
            "Definition": "Indicates how much investors are willing to pay per ₹1 of earnings.",
            "Formula": "P/E = Market Price per Share / Earnings per Share (EPS)",
            "Interpretation": "High P/E = Growth expectations or overvalued; Low P/E = Potential undervaluation or weak growth."
        },
        "Dividend Yield": {
            "Definition": "Shows how much a company pays in dividends relative to its stock price.",
            "Formula": "Dividend Yield = (Annual Dividend per Share / Price per Share) × 100",
            "Interpretation": "Higher yield = Better income; but may also indicate financial stress or lower growth."
        },
        "Book Value": {
            "Definition": "Net asset value of a company per share if it is liquidated.",
            "Formula": "Book Value = (Total Assets – Total Liabilities) / Total Outstanding Shares",
            "Interpretation": "Used to assess if stock is undervalued when compared to market price."
        },
        "Price-to-Book (P/B) Ratio": {
            "Definition": "Compares a company’s market value with its book value.",
            "Formula": "P/B = Market Price per Share / Book Value per Share",
            "Interpretation": "P/B < 1: Possibly undervalued; P/B > 1: Market expects future growth."
        },
        "Quarterly Earnings": {
            "Definition": "Profit (net income) generated by the company in a 3-month period.",
            "Formula": "None",
            "Interpretation": "Positive or better-than-expected earnings often drive stock prices up."
        },
        "Earnings Per Share (EPS)": {
            "Definition": "Indicates how much profit is earned per share.",
            "Formula": "EPS = Net Income / Number of Outstanding Shares",
            "Interpretation": "Higher EPS = Greater profitability and usually better investor confidence."
        },
        "52-Week Change": {
            "Definition": "Percentage change in stock price over the last 52 weeks.",
            "Formula": "52W Change = ((Current Price - Price 1 Year Ago) / Price 1 Year Ago) × 100",
            "Interpretation": "Shows long-term trend; positive = gain, negative = loss."
        },
        "Return on Equity (ROE)": {
            "Definition": "Measures how efficiently a company generates profit from shareholders’ equity.",
            "Formula": "ROE = (Net Income / Shareholders' Equity) × 100",
            "Interpretation": "Higher ROE = Better use of investor funds; low ROE may suggest inefficiency."
        }
    }

    # Print the details neatly
    for term, details in financial_terms.items():
        print(f"\n📘 {term}")
        print(f"   🔹 Definition: {details['Definition']}")
        if details["Formula"] != "None":
            print(f"   🔹 Formula   : {details['Formula']}")
        print(f"   🔹 Interpretation: {details['Interpretation']}")


    return financial_terms